### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tmcw** [kumadasu/tizen-history#1]
What's the license of this repository & image? I'd like to add it to the [Wikipedia page on Tizen](http://en.wikipedia.org/wiki/Tizen#History)

**Comment by kumadasu** [comment]
Wow, I didn't realize this comment.  OK I'll determine license.
What type of license you can use.  Is CC BY 3.0 appropriate?

And let you know that this history contains some mistakes...

**Comment by kumadasu** [comment]
I don't need 'Attribution'.
Is there more appropriate license?
I'm not familiar with OSS licenses.

**Comment by kumadasu** [comment]
I released this project in the Public Domain.
I confirmed it's OK to all commiters Nico and Naruto.
Thanks all.
