### ISSUE TITLE
Sailfish, Ubuntu Touch

### ISSUE THREAD

**Issue by Nyco** [kumadasu/tizen-history#3]
Can you please also add Jolla's Sailfish OS, as well as Ubuntu Touch?

**Comment by kumadasu** [comment]
OK, I'll add it.  It'll take some time to add Sailfish OS for surveying.

**Comment by Nyco** [comment]
Thanks!

Sorry, but...  We could also add the whole Android and webOS families? Thus we could cover a fair amount of opensource/free/libre mobile OS.

What do you think of this?

**Comment by kumadasu** [comment]
Thank you for your pull request about Sailfish OS.

Hmmm, I understand you.
But Android is too famous to add.  I think there are no need to describe its history.

Purpose of this project is to make it easy to understand the background of complicated OSs especially Tizen.
But there are already Ubuntu.  Probably it is the problem...

I can add WebOS but I don't know well about WebOS.  Could you send me its history and reference information?
When and where the OS comes from?

FYI:
You can check about Android and iOS from Unix history.
http://www.levenez.com/unix/

**Comment by Nyco** [comment]
Oh, I almost forgot about Unix history... ;-)

OK to exit Android.

And OK as well for me to provide webOS details.

**Comment by kumadasu** [comment]
OK.  Please send pull request, or some information.

Did you read below about license?
https://github.com/kumadasu/tizen-history/pull/4

May I release this project in 'public domain'?

**Comment by Nyco** [comment]
OK for me for 'public domain'.

**Comment by kumadasu** [comment]
Thanks!  Then I close this issue.  Please pull request or make another issue for webOS.
